Got all the employees, and one employee, and pugged em both to the DOM
Funky-Chickens/workFORCEmanagement pull request #26
Opened 2017-10-11 20:49 UTC by chrismellor08

To test:

Go to localhost:4000/employees
Check to see all employees

AND 

go to localhost:400/employees/[id of your choice between 1-10]
Check to make sure there is data for one employee

2017-10-11 21:00 UTC, Rian501 commented
take out that console log, dude

2017-10-11 21:02 UTC, Rian501 requested changes

2017-10-11 21:02 UTC, Rian501 commented on controllers/employeeCtrl.js
> +      console.log(emps);
right chea

2017-10-11 22:36 UTC, chrismellor08 commented
let console.logs = deleted.

2017-10-12 14:12 UTC, Rian501 commented
Works as advertised.

2017-10-12 14:13 UTC, Rian501 approved these changes

2017-10-12 14:15 UTC, merged